// const sessions = {
//   room1: {
//     users: [
//       {
//         socketId: "socketId1",
//         userId: "userId1",
//         username: "user1",
//         isOnline: true,
//         score: 8,
//         lastRound: 1,
//         imageName: "photoURL1",
//         answerState: "answered",
//         isHost: true,
//       },
//       {
//         socketId: "socketId2",
//         userId: "userId2",
//         username: "user2",
//         isOnline: true,
//         score: 18,
//         lastRound: 1,
//         imageName: "photoURL2",
//         answerState: "notAnswered",
//         isHost: false,
//       },
//       {
//         socketId: "socketId3",
//         userId: "userId3",
//         username: "user3",
//         isOnline: false,
//         score: 5,
//         lastRound: 1,
//         imageName: "photoURL3",
//         answerState: "notAnswered",
//         isHost: false,
//       },
//     ],
//     round: "2",
//     category: { name: "Genre", id: "categoryID1" },
//     subcategory: { name: "Action", id: "categoryID2" },
//     levels: { 1: "levelId" },
//     isGamerunning: true,
//   },
//   room2: {
//     users: [
//       {
//         socketId: "socketId4",
//         userId: "userId4",
//         username: "user4",
//         isOnline: true,
//         score: 20,
//         lastRound: 2,
//         imageName: "photoURL4",
//         rank: 1,
//         answerState: "answered",
//         isHost: true,
//       },
//       {
//         socketId: "socketId5",
//         userId: "userId5",
//         username: "user5",
//         isOnline: true,
//         score: 15,
//         lastRound: 2,
//         imageName: "photoURL5",
//         rank: 2,
//         answerState: "answered",
//         isHost: false,
//       },
//     ],
//     round: "3",
//     currentQuestion: {
//       startedAt: 1620000000000,
//       index: 1,
//     },
//     category: { name: "Genre", id: "categoryID3" },
//     subcategory: { name: "Comedy", id: "categoryID4" },
//     levels: { 1: "levelId" },
//     isGamerunning: false,
//   },
// };
